### PR TITLE
Add test github action

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
See https://github.com/cpuguy83/ipvs/actions/runs/53826658 for runs.
This is just a starter really.
We need another action to run PR validations like DCO sign-off, linting, etc.

**Comment by cpuguy83** [comment]
Nice thing about this is, the ipvs tests have a bunch of skips when running in Circle. Works fine in actions.

**Comment by dims** [comment]
@cpuguy83 looks good! is this ready to merge? (i see the WIP in title still)

**Comment by cpuguy83** [comment]
I removed WIP about an hour ago.

**Comment by thaJeztah** [comment]
I can add the DCO bot

**Comment by dims** [comment]
@thaJeztah will the DCO bot pick up this existing PR?

**Comment by dims** [comment]
Whoops! sorry @cpuguy83 :)

**Comment by dims** [comment]
merging this now.

**Pull request merged**
