### PR TITLE
update dependencies to tagged versions

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/moby/ipvs/pull/31
- [x] depends on https://github.com/moby/ipvs/pull/30

### go.mod: github.com/sirupsen/logrus v1.9.0

Older versions are known to have issues with current Go versions, and
updating the version removes an indirect dependency. Projects should
probably no longer use these old versions of logrus.

full diff: https://github.com/sirupsen/logrus/compare/v1.4.2...v1.9.0

### go.mod: github.com/vishvananda/netns v0.0.2

This project became active again, and now started tagging releases.
Let's update to the current release, which now requires go1.17 as
a minimum.

full diff: https://github.com/vishvananda/netns/compare/0a2b9b5464df...v0.0.2

### CODE REVIEW

**Comment by thaJeztah** [comment]
And this is the last one I had in my queue @AkihiroSuda @neersighted @dims PTAL

**Comment by thaJeztah** [comment]
Once this is merged, we should probably tag a new version; should that be `v1.0.3` or better to do `v1.1.0` (as there's the new go version constraints?)

**Review by neersighted — APPROVED** [review]
LGTM; re: the version question, I'd be inclined to suggest we tag a minor version.

**Comment by thaJeztah** [comment]
Yes, a v1.1.0 is probably best; it keeps our options open to tag a `v1.0.3` if there would be a need. I'll have a look at doing a release (need to look at changes for changelog)

**Comment by thaJeztah** [comment]
I tagged v1.1.0; https://github.com/moby/ipvs/releases/tag/v1.1.0

(@dims @pacoxu FYI)

**Comment by dims** [comment]
thanks @thaJeztah !

**Pull request merged**
