### PR TITLE
remove gotest.tools dependency

### PR DESCRIPTION
**Pull request by thaJeztah**
- alternative to / closes https://github.com/moby/ipvs/pull/28
- relates to https://github.com/kubernetes/kubernetes/issues/114942

### CODE REVIEW

**Comment by dims** [comment]
I prefer this as we completely eliminate 2 packages (as opposed to the PR https://github.com/moby/ipvs/pull/28)

**Review by dims — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> I prefer this as we completely eliminate 2 packages (as opposed to the PR #28)

Yup, same.


Also eyeing logrus, but it appears to be used in quite a few places, so perhaps that's for a later concern.

I do want to have a quick look at;

- updating GitHub actions to test against current versions (we can keep 1.13 as "oldest" version in the matrix; probably no harm
- update golangci-lint (probably needed if we update go versions)
- update the golang.org/x/sys to a tagged release, and update logrus to get old versions out of the dependency tree

**Comment by thaJeztah** [comment]
@cpuguy83 PTAL 🤗

**Comment by pacoxu** [comment]
Great work.

**Review by justincormack — APPROVED** [review]

**Pull request merged**
